---
objects:
  - type: gps_static
    parent_frame: earth
    frame: boat
    gps_pose:
      lat: 39.794273
      lon: -4.081537
      alt: 545.0
    orientation:
      azimuth: 0.0
      bank: 0.0
      elevation: 0.0
