area_scan_mission:
  altitude: 2.0
  speed: 1.0
  corners:
      - [0.0, 0.0]
      - [10.0, 0.0]
      - [10.0, 10.0]
      - [0.0, 10.0]
take_sample_mission:
  altitude: 1.0
  speed: 0.5
boat_mission:
  altitude: 1.0
  speed: 0.5
full_boat_mission:
  altitude: 5.0
  boat_altitude: 2.0
  speed: 1.0