# Aerostack2
/rosout
/tf
/tf_static

# Drone0
/drone0/actuator_command/pose
/drone0/actuator_command/thrust
/drone0/actuator_command/trajectory
/drone0/actuator_command/twist
/drone0/motion_reference/pose
/drone0/motion_reference/thrust
/drone0/motion_reference/trajectory
/drone0/motion_reference/twist
/drone0/platform/info
/drone0/controller/info
/drone0/TakeoffBehavior/_behavior/behavior_status
/drone0/GoToBehavior/_behavior/behavior_status
/drone0/FollowPathBehavior/_behavior/behavior_status
/drone0/LandBehavior/_behavior/behavior_status
/drone0/self_localization/pose
/drone0/self_localization/twist
/drone0/sensor_measurements/battery
/drone0/sensor_measurements/imu
/drone0/sensor_measurements/gps
/drone0/mission_status
/drone0/mission_update
/drone0/sensor_measurements/main_camera/image_raw


# M300
/M300/actuator_command/pose
/M300/actuator_command/thrust
/M300/actuator_command/trajectory
/M300/actuator_command/twist
/M300/motion_reference/pose
/M300/motion_reference/thrust
/M300/motion_reference/trajectory
/M300/motion_reference/twist
/M300/platform/info
/M300/controller/info
/M300/TakeoffBehavior/_behavior/behavior_status
/M300/GoToBehavior/_behavior/behavior_status
/M300/FollowPathBehavior/_behavior/behavior_status
/M300/LandBehavior/_behavior/behavior_status
/M300/self_localization/pose
/M300/self_localization/twist
/M300/sensor_measurements/battery
/M300/sensor_measurements/imu
/M300/sensor_measurements/gps
/M300/mission_status
/M300/mission_update
/M300/sensor_measurements/main_camera/image_raw

# M350
/M350/actuator_command/pose
/M350/actuator_command/thrust
/M350/actuator_command/trajectory
/M350/actuator_command/twist
/M350/motion_reference/pose
/M350/motion_reference/thrust
/M350/motion_reference/trajectory
/M350/motion_reference/twist
/M350/platform/info
/M350/controller/info
/M350/TakeoffBehavior/_behavior/behavior_status
/M350/GoToBehavior/_behavior/behavior_status
/M350/FollowPathBehavior/_behavior/behavior_status
/M350/LandBehavior/_behavior/behavior_status
/M350/self_localization/pose
/M350/self_localization/twist
/M350/sensor_measurements/battery
/M350/sensor_measurements/imu
/M350/sensor_measurements/gps
/M350/mission_status
/M350/mission_update
/M350/sensor_measurements/main_camera/image_raw


